---
title: "Practical_Machine_Learning_Coursera"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Repository for the Practical Machine Learning class, John Hopkins, Coursera.

The pml-coursera-project.Rmd and the pml-coursera-project.html are the R markdown and the HTML files respectively, that describe the analysis performed on the Weight Lifting Exercise Dataset, for the final project of the Practical Machine Learning class.


```{r cars}
#Upload Libraries and Imort data
library(caret)
library(randomForest)
library(rpart)
url.train <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
url.test <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training <- read.csv(url(url.train), na.strings = c("NA", "", "#DIV0!"))
testing <- read.csv(url(url.test), na.strings = c("NA", "", "#DIV0!"))
#We need to verify that the columns in both tables (training, testing) are the same or not
sameColumsName <- colnames(training) == colnames(testing)
colnames(training)[sameColumsName==FALSE]
training<-training[,colSums(is.na(training)) == 0]
testing <-testing[,colSums(is.na(testing)) == 0]
head(colnames(training), 10)
#Deleting 7variables because they are not relevant 
training <- training[,8:dim(training)[2]]
testing <- testing[,8:dim(testing)[2]]
#Data Slicing
set.seed(12345)
inTrain <- createDataPartition(training$classe, p=0.7, list=FALSE)
trainingCV <- training[inTrain,]
testingCV <- training[-inTrain,]
dim(trainingCV)
dim(testingCV)
qplot(accel_arm_x, accel_arm_y, col=classe, data=trainingCV)
qplot(accel_forearm_x, accel_forearm_y, col=classe, data=trainingCV)
#Apply Classification Tree model
modelCTree <- rpart(classe ~ ., data=trainingCV, method="class")
predictionCTree <- predict(modelCTree, testingCV, type="class")
CTree <- confusionMatrix(predictionCTree, testingCV$classe)
CTree
library(rpart.plot)
rpart.plot(modelCTree)
#Apply Random forest model
modelRF <- randomForest(classe ~ ., data=trainingCV, method="class")
predictionRF <- predict(modelRF, testingCV, type="class")
RF <- confusionMatrix(predictionRF, testingCV$classe)
RF
CV <- testingCV
CV$GOODpred <- testingCV$classe == predictionRF
qplot(accel_forearm_x, accel_forearm_y, col=GOODpred, data=CV)
FinalPrediction <- predict(modelRF, testing)
FinalPrediction

```

